# Generated by Django 2.0.2 on 2018-03-13 13:23

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('createdtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('publishedtime', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete='descase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
