# Generated by Django 2.0.2 on 2018-03-09 03:01

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('createdtime', models.DateTimeField(default=datetime.datetime(2018, 3, 9, 3, 1, 58, 204094, tzinfo=utc))),
                ('publishedtime', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete='descase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
