# Generated by Django 2.0.2 on 2018-03-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='用户名')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('url', models.URLField(blank=True, verbose_name='个人网站')),
                ('text', models.TextField(verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('post', models.ForeignKey(on_delete='descase', to='blog.POST')),
            ],
        ),
    ]
