# Generated by Django 2.0.2 on 2018-03-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180318_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='url',
        ),
    ]
