# Generated by Django 2.0.2 on 2018-03-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180320_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='toc',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
