# Generated by Django 2.0.2 on 2018-03-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_toc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='toc',
        ),
    ]
